name: ShinobiTerm
settings:
  base:
    SWIFT_ENABLE_EXPLICIT_MODULES: false
    CLANG_ENABLE_EXPLICIT_MODULES: false
options:
  bundleIdPrefix: com.shinobiterm
  deploymentTarget:
    iOS: "17.0"
  minimumXcodeGenVersion: "2.38.0"
  generateEmptyDirectories: true
packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    branch: main
  Citadel:
    url: https://github.com/orlandos-nl/Citadel.git
    branch: main
targets:
  ShinobiTerm:
    type: application
    platform: iOS
    sources:
      - ShinobiTerm
    dependencies:
      - package: SwiftTerm
      - package: Citadel
    settings:
      base:
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ShinobiTerm/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.shinobiterm.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
