name: ShinobiTerm
settings:
  base:
    SWIFT_ENABLE_EXPLICIT_MODULES: false
    CLANG_ENABLE_EXPLICIT_MODULES: false
options:
  bundleIdPrefix: com.shinobiterm
  deploymentTarget:
    iOS: "17.0"
  minimumXcodeGenVersion: "2.38.0"
  generateEmptyDirectories: true
packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    branch: main
  Citadel:
    url: https://github.com/orlandos-nl/Citadel.git
    branch: main
targets:
  ShinobiTerm:
    type: application
    platform: iOS
    sources:
      - ShinobiTerm
    dependencies:
      - package: SwiftTerm
      - package: Citadel
    configFiles:
      Debug: local.xcconfig
      Release: local.xcconfig
    settings:
      base:
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ShinobiTerm/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.rettuce.shinobiterm
        MARKETING_VERSION: "1.0.7"
        CURRENT_PROJECT_VERSION: 8
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      storeKitConfiguration: ShinobiTerm/Resources/TipJar.storekit
